/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

//import oop.section09.ApplicationMediator;
//import oop.section09.DesktopColleague;
//import oop.section09.MobileColleague;
//import oop.section09.NintendoSwitchColleague;

import oop.section10.*;

public class App {
    public static void main(String[] args) {

//        //section09 mediator
//        ApplicationMediator mediator = new ApplicationMediator();
//        var desktop = new DesktopColleague(mediator);
//        var mobile = new MobileColleague(mediator);
//        var nintendoSwitch = new NintendoSwitchColleague(mediator);
//        mediator.addColleague(desktop);
//        mediator.addColleague(mobile);
//        mediator.addColleague(nintendoSwitch);
//        desktop.send("desktop says, Hello World");
//        mobile.send("mobile says, Hello");

        //section10 facade
        EmpReportFacade dataLoader = new EmpDao();
        new GUIViewer(dataLoader).display();
        new GUIViewer(new ResumeDao()).display();
        new GUIViewer(new EmpResumeDataClient()).display();
        new GUIViewer(new EvaluationDataClient()).display();

        new XmlReporter(dataLoader).display();
        new XmlReporter(new ResumeDao()).display();
        new XmlReporter(new EmpResumeDataClient()).display();
        new XmlReporter(new EvaluationDataClient()).display();
    }
}
